# Build and deploy full React TypeScript app to Azure
name: Build and Deploy React App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build React app and server
        run: |
          # Build the React client and Express server
          npm run build
          
          # Verify build outputs exist
          echo "Checking build outputs:"
          ls -la dist/
          ls -la dist/public/
          
          # Create deployment package structure to match server expectations
          mkdir -p deployment
          
          # Copy built server to deployment root
          cp dist/index.js deployment/
          
          # The server expects 'public' directory to be alongside the server bundle
          # Copy built client assets to public directory at same level as server
          cp -r dist/public deployment/
          
          # Copy videos and images to public directory  
          cp -r client/public/videos deployment/public/ || echo "No videos directory"
          cp -r client/public/images deployment/public/ || echo "No images directory"
          
          # Create production package.json
          cat > deployment/package.json << EOF
          {
            "name": "welcome-home-landscaping",
            "version": "1.0.0",
            "description": "Welcome Home Landscaping and Power Washing Website",
            "main": "index.js",
            "scripts": {
              "start": "node index.js"
            },
            "engines": {
              "node": "20.x"
            },
            "dependencies": {
              "express": "^4.21.2",
              "express-session": "^1.18.1",
              "connect-pg-simple": "^10.0.0",
              "@neondatabase/serverless": "^0.10.4",
              "drizzle-orm": "^0.39.1",
              "drizzle-zod": "^0.7.0",
              "nodemailer": "^7.0.5",
              "zod": "^3.24.2",
              "zod-validation-error": "^3.4.0",
              "memoizee": "^0.4.17",
              "memorystore": "^1.6.7",
              "passport": "^0.7.0",
              "passport-local": "^1.0.0"
            },
            "type": "module"
          }
          EOF
          
          # Verify deployment structure for Linux Azure App Service
          echo "Deployment structure:"
          find deployment -type f -name "*.js" -o -name "*.json" -o -name "*.html" | head -10
          
          # Set proper permissions for Node.js execution on Linux
          chmod +x deployment/index.js
          
          # Create startup command file for Azure Linux App Service
          echo "node index.js" > deployment/startup.sh
          chmod +x deployment/startup.sh

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: deployment/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment-package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AE2F5A84ED97453C9E4EE77CB5CC6425 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_69D25D6979004137A6F97CDED4E4ED9F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8F44B50EF33D408FBFD31504AFCB4812 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-welcomeHome'
          slot-name: 'staging'
          package: '.'