# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - app-welcomeHome

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Clean and build application
        run: |
          # Clean install
          npm ci --legacy-peer-deps
          
          # Build with increased memory for large assets
          NODE_OPTIONS="--max-old-space-size=4096" npm run build
          
          # Verify build outputs
          echo "Build verification:"
          echo "- Server bundle: $(ls -la dist/index.js 2>/dev/null || echo 'MISSING')"
          echo "- Client files: $(ls -la dist/public/index.html 2>/dev/null || echo 'MISSING')"
          echo "- Video files: $(ls -la dist/public/videos/*.mp4 2>/dev/null || echo 'NO VIDEOS FOUND')"

      - name: Prepare Azure deployment
        run: |
          # Copy necessary files to dist
          cp web.config dist/ 2>/dev/null || echo "No web.config found"
          
          # Create production package.json
          cat > dist/package.json << 'EOF'
          {
            "name": "welcome-home-landscaping",
            "version": "1.0.0",
            "type": "module",
            "main": "index.js",
            "scripts": {
              "start": "node index.js"
            },
            "engines": {
              "node": "20.x"
            },
            "dependencies": {
              "express": "^4.21.2",
              "express-session": "^1.18.1",
              "connect-pg-simple": "^10.0.0",
              "memorystore": "^1.6.7",
              "passport": "^0.7.0",
              "passport-local": "^1.0.0",
              "drizzle-orm": "^0.39.1",
              "zod": "^3.24.2",
              "zod-validation-error": "^3.4.0",
              "ws": "^8.18.0",
              "@neondatabase/serverless": "^0.10.4",
              "drizzle-zod": "^0.7.0"
            }
          }
          EOF
          
          echo "Final deployment structure:"
          ls -la dist/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AE2F5A84ED97453C9E4EE77CB5CC6425 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_69D25D6979004137A6F97CDED4E4ED9F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8F44B50EF33D408FBFD31504AFCB4812 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-welcomeHome'
          slot-name: 'Production'
          package: './dist'