# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - app-welcomeHome

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install all dependencies for build
        run: |
          # Install all dependencies including dev dependencies for build
          npm install --legacy-peer-deps

      - name: Build application
        run: |
          # Build with increased memory for large assets
          NODE_OPTIONS="--max-old-space-size=4096" npm run build
          
          # Verify build outputs
          echo "Build verification:"
          echo "- Server bundle: $(ls -la dist/index.js 2>/dev/null || echo 'MISSING')"
          echo "- Client files: $(ls -la dist/public/index.html 2>/dev/null || echo 'MISSING')"

      - name: Create deployment package
        run: |
          # Create deployment structure
          mkdir -p deployment
          
          # Copy built server bundle
          mkdir -p deployment/server
          cp dist/index.js deployment/server/
          
          # Copy client assets to expected location
          mkdir -p deployment/server/public
          cp -r dist/public/* deployment/server/public/
          
          # Create production package.json with only runtime dependencies
          cat > deployment/package.json << 'EOF'
          {
            "name": "welcome-home-landscaping",
            "version": "1.0.0",
            "type": "module",
            "scripts": {
              "start": "node server/index.js"
            },
            "engines": {
              "node": ">=20.0.0"
            },
            "dependencies": {
              "express": "^4.21.2",
              "express-session": "^1.18.1",
              "connect-pg-simple": "^10.0.0",
              "memorystore": "^1.6.7",
              "passport": "^0.7.0",
              "passport-local": "^1.0.0",
              "drizzle-orm": "^0.39.1",
              "zod": "^3.24.2",
              "zod-validation-error": "^3.4.0",
              "ws": "^8.18.0",
              "@neondatabase/serverless": "^0.10.4",
              "drizzle-zod": "^0.7.0"
            }
          }
          EOF

      - name: Zip artifact for deployment
        run: |
          cd deployment
          zip -r ../release.zip ./*
          cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AE2F5A84ED97453C9E4EE77CB5CC6425 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_69D25D6979004137A6F97CDED4E4ED9F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8F44B50EF33D408FBFD31504AFCB4812 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-welcomeHome'
          slot-name: 'Production'
          package: .