# Build and deploy full React TypeScript app to Azure
name: Build and Deploy React App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build React app and server
        run: |
          # Build the React client first
          npm run vite build
          
          # Build the server with proper production configuration
          # Exclude vite-related dependencies to prevent bundling issues
          npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outfile=dist/index.js --define:process.env.NODE_ENV='"production"' --external:vite --external:@vitejs/plugin-react --external:@replit/vite-plugin-cartographer --external:@replit/vite-plugin-runtime-error-modal
          
          # Verify build outputs exist
          echo "Checking build outputs:"
          ls -la dist/
          ls -la dist/public/
          
          # Create deployment package structure to match server expectations
          mkdir -p deployment
          
          # Copy built server to deployment root
          cp dist/index.js deployment/
          
          # The server expects 'public' directory to be alongside the server bundle
          # Copy built client assets to public directory at same level as server
          cp -r dist/public deployment/
          
          # Copy videos and images to public directory  
          cp -r client/public/videos deployment/public/ || echo "No videos directory"
          cp -r client/public/images deployment/public/ || echo "No images directory"
          
          # Fix the default port in the built server file for Azure compatibility
          sed -i 's/process\.env\.PORT || '\''5000'\''/process.env.PORT || '\''8080'\''/g' deployment/index.js || echo "Port replacement failed"
          
          # Add better error handling for Azure startup
          sed -i 's/throw err;/console.error("Application error:", err); process.exit(1);/g' deployment/index.js || echo "Error handling update failed"
          
          # Verify the port change was applied
          if grep -q "process.env.PORT || '8080'" deployment/index.js; then
            echo "✓ Port successfully changed to 8080 default"
          else
            echo "⚠ Port change may not have been applied"
          fi
          
          # Verify deployment structure for Linux Azure App Service
          echo "Deployment structure:"
          find deployment -type f -name "*.js" -o -name "*.json" -o -name "*.html" | head -10
          
          # Set proper permissions for Node.js execution on Linux
          chmod +x deployment/index.js
          
          # Create enhanced startup script with better error handling for Azure
          cat > deployment/startup.sh << 'EOF'
          #!/bin/bash
          echo "Starting Welcome Home Landscaping application..."
          echo "Node.js version: $(node --version)"
          echo "Environment: $NODE_ENV"
          echo "Port: $PORT"
          
          # Set NODE_ENV to production if not set
          export NODE_ENV=${NODE_ENV:-production}
          
          # Start the application with proper error handling and logging
          node index.js 2>&1 | tee /home/LogFiles/application.log
          EOF
          chmod +x deployment/startup.sh
          
          # Also create a package.json with better Azure-specific configuration
          cat > deployment/package.json << EOF
          {
            "name": "welcome-home-landscaping",
            "version": "1.0.0",
            "description": "Welcome Home Landscaping and Power Washing Website",
            "main": "index.js",
            "scripts": {
              "start": "node index.js"
            },
            "engines": {
              "node": ">=18.0.0"
            },
            "dependencies": {
              "express": "^4.21.2",
              "express-session": "^1.18.1",
              "connect-pg-simple": "^10.0.0",
              "@neondatabase/serverless": "^0.10.4",
              "drizzle-orm": "^0.39.1",
              "drizzle-zod": "^0.7.0",
              "nodemailer": "^7.0.5",
              "zod": "^3.24.2",
              "zod-validation-error": "^3.4.0",
              "memoizee": "^0.4.17",
              "memorystore": "^1.6.7",
              "passport": "^0.7.0",
              "passport-local": "^1.0.0",
              "ws": "^8.16.0"
            },
            "type": "module"
          }
          EOF

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: deployment/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment-package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AE2F5A84ED97453C9E4EE77CB5CC6425 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_69D25D6979004137A6F97CDED4E4ED9F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8F44B50EF33D408FBFD31504AFCB4812 }}

      - name: List deployment contents for verification
        run: |
          echo "Deployment package contents:"
          find . -type f | head -20
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-welcomeHome'
          slot-name: 'staging'
          package: '.'